[build]
  base = "REMS"
  command = "composer install --no-interaction --no-suggest && php artisan optimize && php artisan route:cache && php artisan config:cache && php artisan view:cache"
  publish = "REMS/public"
